# Generated by Django 5.2.15 on 2026-08-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ledger_name', models.CharField(max_length=255)),
                ('parent', models.CharField(blank=True, default='', max_length=255)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('voucher_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('tally_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='tallyapp.tallyinstance')),
            ],
        ),
        migrations.CreateModel(
            name='EMDLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='Deposits - EMD', max_length=150)),
                ('emd_status', models.CharField(default='Not Closed', max_length=20)),
                ('emd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('closed_in_month', models.CharField(blank=True, max_length=20, null=True)),
                ('financial_year', models.CharField(blank=True, default='', max_length=9)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emd_info', to='tallyapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=150)),
                ('master_id', models.CharField(blank=True, default='', max_length=50)),
                ('voucher_no', models.CharField(blank=True, default='', max_length=100)),
                ('voucher_type', models.CharField(blank=True, default='', max_length=100)),
                ('party_ledger', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.CharField(blank=True, default='', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('narration', models.TextField(blank=True, default='')),
                ('financial_year', models.CharField(blank=True, default='', max_length=9)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='tallyapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherBreakdown',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ledger_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_lines', to='tallyapp.voucher')),
            ],
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['tally_instance', 'ledger_name'], name='tallyapp_le_tally_i_8013a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('tally_instance', 'ledger_name'), name='uniq_ledger_per_instance'),
        ),
        migrations.AddIndex(
            model_name='emdledger',
            index=models.Index(fields=['emd_status'], name='tallyapp_em_emd_sta_c6e71f_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['ledger', 'financial_year'], name='tallyapp_vo_ledger__3c3ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['guid'], name='tallyapp_vo_guid_39b70f_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('ledger', 'guid'), name='uniq_voucher_per_ledger'),
        ),
        migrations.AddIndex(
            model_name='voucherbreakdown',
            index=models.Index(fields=['voucher'], name='tallyapp_vo_voucher_9c4e82_idx'),
        ),
    ]
