# Generated by Django 5.2.15 on 2026-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_ledger_emdledger_voucher_voucherbreakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emdledger',
            name='closed_in_month',
        ),
        migrations.RemoveField(
            model_name='emdledger',
            name='emd_amount',
        ),
        migrations.AddField(
            model_name='emdledger',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='emdledger',
            name='nett_transactions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='emdledger',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
