# Generated by Django 5.2.15 on 2026-09-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0002_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
