# Generated by Django 5.2.15 on 2026-09-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0003_resume_is_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
