# Generated by Django 5.2.15 on 2026-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0004_parsedprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='known_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
