# Generated by Django 5.2.15 on 2026-09-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0006_parsedprofile_candidate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='ocr_deep_dive_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='parse_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
