# Generated by Django 5.2.15 on 2026-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0007_parsedprofile_ocr_deep_dive_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='hobbies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='training',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
