# Generated by Django 5.2.15 on 2026-09-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0008_parsedprofile_hobbies_parsedprofile_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=50)),
                ('source_format', models.CharField(choices=[('file', 'File'), ('json', 'JSON'), ('text', 'Text')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='bulkresume/jds/%Y/%m/%d/')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, choices=[('db_profile', 'DB Profile'), ('parsed', 'Freshly Parsed')], max_length=20)),
                ('extraction_method', models.CharField(blank=True, max_length=30, null=True)),
                ('parse_score', models.FloatField(blank=True, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('candidate_profile', models.JSONField(blank=True, default=dict)),
                ('match_method', models.CharField(blank=True, max_length=30)),
                ('match_percent', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('matched_qualifications', models.JSONField(blank=True, default=list)),
                ('missing_qualifications', models.JSONField(blank=True, default=list)),
                ('experience_match', models.CharField(blank=True, max_length=255)),
                ('field_breakdown', models.JSONField(blank=True, default=list)),
                ('strengths_summary', models.TextField(blank=True)),
                ('gaps_summary', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bulkresume.jobdescription')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='bulkresume.resume')),
            ],
        ),
    ]
