# Generated by Django 5.2.15 on 2026-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0009_jobdescription_resumematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20),
        ),
    ]
