# Generated by Django 5.2.15 on 2026-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0010_alter_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ocr_deep_dive_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ocr_deep_dive_text',
            field=models.TextField(blank=True),
        ),
    ]
