# Generated by Django 5.2.15 on 2026-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0011_resume_ocr_deep_dive_attempted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='total_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
