# Generated by Django 5.2.15 on 2026-09-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0012_parsedprofile_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='parsedprofile',
            name='total_experience',
        ),
    ]
