# Generated by Django 5.2.15 on 2026-09-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0013_remove_parsedprofile_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='total_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
