# Generated by Django 5.2.15 on 2026-09-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0014_parsedprofile_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedprofile',
            name='projects',
        ),
    ]
