# Generated by Django 5.2.15 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkresume', '0015_remove_parsedprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
